spring.application.name=interview

#swagger props
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#management endpoints
management.info.env.enabled=true
management.info.build.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health,info
info.application.name = Prime Number Generator Service
info.application.description= A Springboot RESTful service which calculates and returns all the prime numbers up to and including a number provided.